# @name signIn
POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
  "username": "user5",
  "password": "SD2fsd23@34%"
}
###
@auth = {{signIn.response.body.accessToken}}

###
GET http://localhost:3000/cards
Content-Type: application/json
Authorization: Bearer {{auth}}


{
  "status": "New"
}

###

POST http://localhost:3000/cards
Content-Type: application/json
Authorization: Bearer {{auth}}

{
  "text": "butter UP123PER",
  "filePath": "this-is-test-2.jpg"
}
###

@id = 8aba35fd-5644-49d5-bc24-e9ee30830773

GET http://localhost:3000/cards/{{id}}
Authorization: Bearer {{auth}}
###

PATCH http://localhost:3000/cards/{{id}}/increase-view
Authorization: Bearer {{auth}}

###

DELETE http://localhost:3000/cards/{{id}}
Authorization: Bearer {{auth}}
